#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UpcomingMoviesAndroid.Resource", IsApplication=true)]

namespace UpcomingMoviesAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_search_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int noimage_w300 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int noimage_w500 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int backButton = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int buttonDetails = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int imgViewMovie = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int imgViewMovieListItem = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int innerLinearLayout = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int innerLinearLayoutMovieListItem = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int listViewMovies = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int loadingPanel = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int loadingPanelMain1 = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int menu_search = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int progressBarMain = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int progressBarMainLoading = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int recyclerViewMovies = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int scrollViewDetails = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int scrollViewInnerLinearLayout = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int searchViewMovies = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int textViewGenres = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textViewOverview = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int textViewReleaseDate = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int textViewTitle = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int toolbarMain = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int txtViewMovieListItemGenres = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int txtViewMovieListItemReleaseDate = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int txtViewMovieListItemTitle = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Details = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoadingActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainLayoutv7 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MovieListItemLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Toolbar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int top_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int backButton = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int details_activity_name = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int details_button = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int details_genres = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int details_overview = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int details_release_date = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int details_title = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int main_data_load_error = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int main_loading = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int not_defined_genre = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int search_hint = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int search_name = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int upcoming_movies = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int UpcomingMoviesTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
